#!/bin/sh

tmux_pid=$(pgrep -P$1 tmux)
session_name=$(grep -zFxA1 -- '-s' < /proc/$tmux_pid/cmdline | cut -b3-)
current_command=$(tmux ls -F '#{session_name} #{pane_current_command}' \
    | grep -F "$session_name " | cut -f2 -d' ')

if [ "$current_command" = "mcabber" ]; then
    echo tmux send -t $session_name /esay enter i
    tmux send -t $session_name /esay enter 'i' c-r '*' enter
else
    tmux neww -t $session_name "$(cat <<EOF
        $EDITOR $2;
        tmux loadb $2 \; pasteb -t $session_name:-1 ;
        rm $2 ;
EOF
    )"
fi
